version: "3.5"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: article
    ports:
      - 3306:3306
    command: ["mysqld", "--character-set-server", "utf8mb4"]
  api_dev:
    build:
      context: .
      target: builder
    ports:
      - 9090:9090
    volumes:
      - ./app:/go/src/github.com/zawawahoge/quiz-practice-api/app
    tty: true
    environment:
      MYSQL_CONNECTION: ${MYSQL_CONNECTION}
    depends_on:
      - db
    command: ["/bin/bash", "wait.sh", "db", "root", "password", "article", "go", "run", "app/cmd/app/*.go"]
