FROM golang:1.13 as builder

ENV GO111MODULE on
ENV PROJECT_ROOT /go/src/github.com/zawawahoge/quiz-practice/api
WORKDIR $PROJECT_ROOT

RUN apt-get update -y

COPY go.mod .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -o build ./reverse-proxy
